export const prettyColors = [
    { name: "lightPink", hexCode: "#ffb6c1", fontColor: "black" },
    { name: "navajoWhite", hexCode: "#ffdead", fontColor: "black" },
    { name: "gold", hexCode: "#ffd700", fontColor: "black" },
    { name: "powderBlue", hexCode: "#b0e0e6", fontColor: "black" },
    { name: "lightBlue", hexCode: "#add8e6", fontColor: "black" },
    { name: "paleGreen", hexCode: "#98fb98", fontColor: "black" },
    { name: "lightSalmon", hexCode: "#ffa07a", fontColor: "black" },
    { name: "salmon", hexCode: "#fa8072", fontColor: "black" },
    { name: "sandyBrown", hexCode: "#f4a460", fontColor: "black" },
    { name: "plum", hexCode: "#dda0dd", fontColor: "black" },
    { name: "mediumOrchid", hexCode: "#ba55d3", fontColor: "white" },
    { name: "mediumPurple", hexCode: "#9370db", fontColor: "white" },
    { name: "skyBlue", hexCode: "#87ceeb", fontColor: "black" },
    { name: "mediumSpringGreen", hexCode: "#00fa9a", fontColor: "black" },
    { name: "aquamarine", hexCode: "#7fffd4", fontColor: "black" },
    { name: "bisque", hexCode: "#ffe4c4", fontColor: "black" },
    { name: "hotPink", hexCode: "#ff69b4", fontColor: "black" },
    { name: "turquoise", hexCode: "#40e0d0", fontColor: "black" },
    { name: "darkTurquoise", hexCode: "#00ced1", fontColor: "white" },
    { name: "steelBlue", hexCode: "#4682b4", fontColor: "white" },
];